swarm-demo:
  image: tauffredou/swarm-demo
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "/Users/thomas/.docker/machine/machines/mhs-demo0:/certs/"
  ports:
  - 8080:8080
  container_name: swarm-demo
  environment:
    DOCKER_HOST: tcp://192.168.99.103:3376
    DOCKER_CERT_PATH: "/certs"
